[project]
name = "gridlock"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Loaf the Computerphile", email = "53319491+loafthecomputerphile@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "geopandas>=1.1.4",
    "geopy>=2.5.0",
    "openpyxl>=3.1.5",
    "pandas>=3.0.6",
    "pdfplumber>=0.11.10",
    "pyproj>=3.8.0",
    "shapely>=2.1.2",
    "uvicorn>=0.54.0",
]

[project.scripts]
gridlock = "gridlock:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "httpx>=0.28.1",
]
